GitHub contribution help docs
beetboxvm/beetbox pull request #363
Opened 2017-01-11 00:36 UTC by christopher-hopper

## Proposed Changes

- Add [Github Pull Request template](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) to help contributors describe their work
- Create a [Github Contributing doc](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) shown as a link when people create a pull request

## Relates To

- Issue #255 

## Notify

- @alexdesignworks

2017-01-11 01:14 UTC, AlexSkrypnyk requested changes

2017-01-11 01:14 UTC, alexdesignworks commented on .github/CONTRIBUTING.md
> +Please submit a [GitHub Pull Request to Beetbox][] with a clear list of what you've done.
broken link?

2017-01-11 01:14 UTC, alexdesignworks commented on .github/PULL_REQUEST_TEMPLATE.md
> +- @beetboxvm/octoteam
is this a correct account?

2017-01-11 01:19 UTC, christopher-hopper commented on .github/PULL_REQUEST_TEMPLATE.md
> +- @beetboxvm/octoteam
As I'm not a member of the beetboxvm organisation, I can't see your / their teams. If I could, I'd tell you that is probably a non-existent team. 

Octocat is also an account you probably wouldn't notify. 

These are what are called examples.

2017-01-11 01:20 UTC, alexdesignworks commented on .github/PULL_REQUEST_TEMPLATE.md
> +- @beetboxvm/octoteam
cool, thanks for the explanation
@thom8 what would be the correct groups for notification

2017-01-11 01:21 UTC, AlexSkrypnyk approved these changes
Thanks for your contribution @christopher-hopper. Looks awesome!

2017-01-11 06:48 UTC, thom8 commented on .github/PULL_REQUEST_TEMPLATE.md
> +- @beetboxvm/octoteam
@alexdesignworks we currently get notifications on the `drupalmel` slack channel so probably don't need this.

Anyone is welcome to join @ http://melbourne.drupal.org.au/

2017-01-11 06:53 UTC, christopher-hopper commented
Is that documented anywhere?

On Wed, Jan 11, 2017, 17:48 Thom Toogood <notifications@github.com> wrote:

> *@thom8* commented on this pull request.
> ------------------------------
>
> In .github/PULL_REQUEST_TEMPLATE.md
> <https://github.com/beetboxvm/beetbox/pull/363>:
>
> > @@ -0,0 +1,14 @@
> +## Proposed Changes
> +
> +- Change
> +- Update
> +- Fix
> +
> +## Relates To
> +
> +- Issue #0
> +
> +## Notify
> +
> +- @octocat
> +- @beetboxvm/octoteam
>
> @alexdesignworks <https://github.com/alexdesignworks> we currently get
> notifications on the drupalmel slack channel so probably don't need this.
>
> Anyone is welcome to join @ http://melbourne.drupal.org.au/
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/beetboxvm/beetbox/pull/363>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAbnox6Qj2Y9YYck-Os1LaICSyxrQ4yvks5rRHspgaJpZM4LgEDu>
> .
>

2017-01-11 07:00 UTC, thom8 commented
It's more of an "unofficial" channel which most contributors are in, we have talked about creating an offical channel but haven't really felt the need so far.

2017-01-11 07:03 UTC, christopher-hopper commented
Then let's come up with an official set of tools and standards that any new
contributor will understand. If someone sees parallel work and wants to
reach out to another GitHub contributor, they'll understand use of the @
notify to bring that person into the discussion

On Wed, Jan 11, 2017, 18:00 Thom Toogood <notifications@github.com> wrote:

> It's more of an "unofficial" channel which most contributors are in, we
> have talked about creating an offical channel but haven't really felt the
> need so far.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/beetboxvm/beetbox/pull/363#issuecomment-271793775>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAbno866V5LZAiIA1PJgu482L9D1Tfggks5rRH4IgaJpZM4LgEDu>
> .
>

2017-01-11 07:08 UTC, christopher-hopper commented
I'll remove the team @ mention as its obviously not needed here

On Wed, Jan 11, 2017, 18:00 Thom Toogood <notifications@github.com> wrote:

> It's more of an "unofficial" channel which most contributors are in, we
> have talked about creating an offical channel but haven't really felt the
> need so far.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/beetboxvm/beetbox/pull/363#issuecomment-271793775>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAbno866V5LZAiIA1PJgu482L9D1Tfggks5rRH4IgaJpZM4LgEDu>
> .
>

2017-01-11 07:11 UTC, thom8 commented
sounds good -- slack has been a good back channel, it's sometimes a bit overkill to add an issue for a simple question.

Plus, it alerts us of all issues, PRs, commits, new releases (tags) & build status on Atlas.

2017-01-12 07:49 UTC, thom8 approved these changes

2017-01-12 07:49 UTC, merged